# Generated by Django 3.1.7 on 2021-05-26 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type_id', models.CharField(choices=[('نظري', 'نظري'), ('عملي', 'عملي')], max_length=50, null=True)),
                ('time_id', models.CharField(choices=[('الامتحان الأول', 'الامتحان الأول'), ('التكميلي', 'التكميلي'), ('الاعادة', 'الاعادة')], max_length=50, null=True)),
                ('mark', models.IntegerField(null=True)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.session')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
    ]
