# Generated by Django 3.1.7 on 2021-05-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.IntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=120, null=True)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('num_of_session', models.IntegerField(null=True)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
