# Generated by Django 3.1.7 on 2021-05-26 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position', '0001_initial'),
        ('person', '0001_initial'),
        ('period', '0001_initial'),
        ('course', '0001_initial'),
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.IntegerField(primary_key=True, serialize=False)),
                ('session_number', models.IntegerField(null=True)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('course_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('level_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='level.level')),
                ('position_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='position.position')),
                ('teacher_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('time_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='period.time')),
            ],
        ),
        migrations.CreateModel(
            name='Session_Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
                ('session_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session.session')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
    ]
