# Generated by Django 3.1.7 on 2021-07-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_id',
            field=models.IntegerField(null=True),
        ),
    ]
