# Generated by Django 3.1.7 on 2021-07-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0002_level_level_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='level_id',
        ),
    ]
