# Generated by Django 3.1.7 on 2021-05-26 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('position_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('create_date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
